CREATE TABLE [dbo].[COP_SalesOrder] (
    [ID]             INT             IDENTITY (1, 1) NOT NULL,
    [COP_Source]     NVARCHAR (10)   CONSTRAINT [DF_COP_SalesOrder_COP_Source] DEFAULT ('') NULL,
    [TG003]          NVARCHAR (50)   CONSTRAINT [DF_COP_SalesOrder_TH0011] DEFAULT ('') NULL,
    [TH001]          NVARCHAR (50)   CONSTRAINT [DF_COP_SalesOrder_TH001] DEFAULT ('') NOT NULL,
    [TH002]          NVARCHAR (50)   NOT NULL,
    [TH003]          NVARCHAR (50)   NOT NULL,
    [TH004]          NVARCHAR (40)   NULL,
    [TH005]          NVARCHAR (120)  NULL,
    [TH006]          NVARCHAR (120)  NULL,
    [TH009]          NVARCHAR (6)    NULL,
    [TH007]          NVARCHAR (10)   NULL,
    [TH008]          NUMERIC (16, 3) NULL,
    [SumQty]         NUMERIC (16, 3) CONSTRAINT [DF_COP_SalesOrder_SumQty] DEFAULT ((0)) NULL,
    [TH012]          NUMERIC (21, 6) NULL,
    [TH013]          NUMERIC (21, 6) NULL,
    [TG011]          NVARCHAR (4)    NULL,
    [TG012]          NUMERIC (16, 3) NULL,
    [TH037]          NUMERIC (21, 6) NULL,
    [TH038]          NUMERIC (21, 6) NULL,
    [SumAmt]         NUMERIC (21, 6) CONSTRAINT [DF_COP_SalesOrder_SumAmt] DEFAULT ((0)) NULL,
    [TH024]          NUMERIC (16, 3) NULL,
    [TH014]          NVARCHAR (4)    NULL,
    [TH015]          NVARCHAR (11)   NULL,
    [TH016]          NVARCHAR (4)    NULL,
    [TH018]          NVARCHAR (255)  CONSTRAINT [DF_COP_SalesOrder_TH018] DEFAULT ('') NULL,
    [TC012]          NVARCHAR (20)   CONSTRAINT [DF_COP_SalesOrder_TH0181] DEFAULT ('') NULL,
    [SerialNosJson]  NVARCHAR (MAX)  NULL,
    [TA001]          NCHAR (4)       NULL,
    [TA002]          NCHAR (11)      NULL,
    [PlanNumber]     NVARCHAR (40)   NULL,
    [TA026]          NVARCHAR (4)    NULL,
    [TA027]          NVARCHAR (11)   NULL,
    [TA028]          NVARCHAR (4)    NULL,
    [SerialNosJson1] NVARCHAR (MAX)  NULL,
    [TA0011]         NCHAR (4)       NULL,
    [TA0021]         NCHAR (11)      NULL,
    [PlanNumber1]    NVARCHAR (40)   NULL,
    [CustomerNo]     VARCHAR (20)    NULL,
    [CustomerName]   NVARCHAR (80)   NULL,
    [Memo]           NVARCHAR (500)  NULL,
    [FooterFlag]     VARCHAR (1)     CONSTRAINT [DF_COP_SalesOrder_FooterFlag] DEFAULT ('') NULL,
    [aStatus]        VARCHAR (1)     NULL,
    [Creator]        NVARCHAR (40)   NULL,
    [CreateTime]     DATETIME        NULL,
    [Modifier]       NVARCHAR (40)   NULL,
    [ModiTime]       DATETIME        NULL,
    CONSTRAINT [PK_COP_SalesOrder] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
