name: deploy-prod

on:
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: [self-hosted, docker, proril-sales-center]

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          ref: main

      - name: Deploy
        run: |
          export APP_PORT=51061
          docker compose -f docker-compose.prod.yml up -d --build --remove-orphans

      - name: Show recent logs
        if: always()
        run: docker compose -f docker-compose.prod.yml logs --tail=50

      - name: Clean up old images
        run: docker image prune -f
